### ISSUE TITLE
希望能更進windows視窗大小

### ISSUE THREAD

**Issue by Bianca2000** [Predidit/oneAnime#1]
很好用，不用下載動畫就能換源並看到彈幕
但用視窗較小的電腦看會出現主程式超出螢幕的問題
![image](https://github.com/Predidit/oneAnime/assets/58384118/341d732c-9f0a-47ff-80d9-4b807eccb038)

希望後續能有手動加上彈幕的功能或加上彈幕源的功能，因為有時候還是匹配不上

**Comment by Predidit** [comment]
好耶，本项目的第一个 Issue

能透露一下出现显示问题的设备的屏幕解析度吗，这可以帮助我定位问题。

关于弹幕匹配问题，部分番剧的大陆译名与台湾译名有微妙的区别，例如 “Rewrite 2nd Season” 与 "Rewrite 第二季"，本项目使用的聚合弹幕接口以大陆译名为准，故有时会出现弹幕丢失的问题。

我在尝试编写一个新的弹幕解析器，会在设置中提供切换，它将只从动画疯拉取弹幕，可以一定程度上解决该问题，但是我不能保证问题的改善，因为动画疯的版权实际上也不够齐全。

**Comment by Bianca2000** [comment]
看了下大概是這樣，因為我筆電大約是14吋[30.2cm*18.9cm]
![image](https://github.com/Predidit/oneAnime/assets/58384118/bd78a072-08f0-4e83-a7f2-df11d189fc52)
所以使用一些主程式需要自己調整視窗大小，所以如果能有辦法調整播放器跟主視窗的尺寸就更好了

彈幕的問題確實不那麼要緊畢竟用這個算是有點佔便宜的用法哈哈
像彈彈PLAY一樣能自訂義來源就很好啦

**Comment by Predidit** [comment]
在这样的显示设置下，解析度问题已经成功复现。

但是应该我不会开放调整视窗大小功能，这会导致布局错误，在15.6寸的1080P屏幕上，windows 建议缩放比例为 125%。这一比例下没有显示问题。

我可以尝试让本程序的缩放比例在1080P下不跟随系统，强制设定为 125%。但这并不优雅。

如果可能的话，可以尝试调整全局屏幕缩放比例为 125% ， 这会解决你遇到的大多数软件的问题。如果觉得 125% 比例显示效果无法接受，我会尝试在后续的版本更新中添加上面提到的实现。

**Comment by Bianca2000** [comment]
> 在这样的显示设置下，解析度问题已经成功复现。
> 
> 但是应该我不会开放调整视窗大小功能，这会导致布局错误，在15.6寸的1080P屏幕上，windows 建议缩放比例为 125%。这一比例下没有显示问题。
> 
> 我可以尝试让本程序的缩放比例在1080P下不跟随系统，强制设定为 125%。但这并不优雅。
> 
> 如果可能的话，可以尝试调整全局屏幕缩放比例为 125% ， 这会解决你遇到的大多数软件的问题。如果觉得 125% 比例显示效果无法接受，我会尝试在后续的版本更新中添加上面提到的实现。

了解，謝謝，我用外接顯示器就好多了
