### ISSUE TITLE
名字和播放链接不一致

### ISSUE THREAD

**Issue by hanchenzichen** [Predidit/oneAnime#11]
原网站名字和动漫是一致的，但是oneime不一致，第七王子点进去播放的其实是神明渴求着游戏的
![Screenshot_2024-04-10-06-55-58-504_com.predidit.oneanime.jpg](https://github.com/Predidit/oneAnime/assets/78671278/10b8ee9d-4240-4d0e-90cf-e9a9b67950b2)

**Comment by Predidit** [comment]
使用最新版本试试 （1.1.5）

**Comment by Predidit** [comment]
我这边使用最新版本测试是没有发现问题的，如果没有进一步的信息，我会在稍晚时候关闭此 issue

**Comment by hanchenzichen** [comment]
> 我这边使用最新版本测试是没有发现问题的，如果没有进一步的信息，我会在稍晚时候关闭此 issue

覆盖升级还会有这个问题，然后我清数据就好了![Screenshot_2024-04-10-13-26-46-850_com.predidit.oneanime.jpg](https://github.com/Predidit/oneAnime/assets/78671278/eec6d153-12e4-4f62-aa5e-5b5c27f94459)

**Comment by Predidit** [comment]
这两部动漫在源站上的链接曾经是错误的，后来被修正，这可能导致问题。

我先关闭这个 Issue ，如果出现其他的错误，可以再打开 Issue

**Comment by long1512448773** [comment]
哟这不是韩晨吗？喜欢道德定义对错的人？  正常人都知道，喜欢让别人看剧本走路的人，无论对方怎么样，都会出错，因为你是编剧，一个喜欢玩网络的人，给自己设置心里的防线太多了，非要把错，讲给对方，讲不过还骂人，是不是你？你种人，和美国那种杂交人种一个样子啊！ 道德与法治，被这种定义简直就是这种人的悲哀，被打脸了，无能狂怒，狺狺狂吠，真以为自己是世界霸主，人人都要尊重你？照着你的剧本走？

**Comment by Predidit** [comment]
> 哟这不是韩晨吗？喜欢道德定义对错的人？  正常人都知道，喜欢让别人看剧本走路的人，无论对方怎么样，都会出错，因为你是编剧，一个喜欢玩网络的人，给自己设置心里的防线太多了，非要把错，讲给对方，讲不过还骂人，是不是你？你种人，和美国那种杂交人种一个样子啊！ 道德与法治，被这种定义简直就是这种人的悲哀，被打脸了，无能狂怒，狺狺狂吠，真以为自己是世界霸主，人人都要尊重你？照着你的剧本走？

我注意到您的行为和语言不符合Github行为准则。我已经向GitHub举报了您的滥用行为。

您应该为自己的言行感到羞愧。
