### ISSUE TITLE
Windows 1.15 版本点击番剧后报错 RangeError (index): Invalid value: Valid value range is empty: -1

### ISSUE THREAD

**Issue by mavnp** [Predidit/oneAnime#14]
![Snipaste_2024-04-16_09-40-27](https://github.com/Predidit/oneAnime/assets/92003405/50e33c21-0247-47de-981b-18b282954e75)

第一次使用 windows 版本时没有出现任何问题，但第二天也就是今天我使用时发现加载缓慢且报错（我亦让我的朋友试了一下，也出现了该问题）。
我暂时无法确认导致该问题的原因，抱歉，辛苦您探寻一下

**Comment by Predidit** [comment]
抱歉，最近太忙了，这两天才抽开身。

请问问题现在还存在吗。
