### ISSUE TITLE
Android端样式错误

### ISSUE THREAD

**Issue by timelic** [Predidit/oneAnime#15]
如图，播放界面下半部分的左边距为0。

![](https://github.com/Predidit/oneAnime/assets/20257354/49ad5008-3543-4499-bf13-a2afb3b08f5f)

**Comment by timelic** [comment]
另外请求适配高刷新率。

**Comment by Predidit** [comment]
1.1.6 版本已经发布，高刷新率支持包含在本次更新中。

如果有其他问题，欢迎继续回复此 Issue。

没有的话。我将在稍晚时候关闭此 Issue。
