### ISSUE TITLE
缺乏对里番的支持

### ISSUE THREAD

**Issue by qxqxqxx** [Predidit/oneAnime#17]
Anime1除了[表站](https://anime1.me/)之外，还有一个专门放里番的[里站](https://anime1.pw/)。oneAnime虽然不会从里站获取视频链接，但是会完整地抓取Anime1上的新番表，这可能会导致一些里番混入其中（比如本季度的《明明只是個煙霧彈配角，卻得到完美王子的寵愛》）。

如果点击这个里番，就会从这里报`RangeError (index): Invalid value: Valid value range is empty: -1`的错：
https://github.com/Predidit/oneAnime/blob/bdfabfa80e8ea3b31a2d305c75ae762e677a5630/lib/pages/timeline/timeline_page.dart#L232

如果oneAnime不打算支持里番的话，不妨加入里番判断的逻辑，完善报错信息。最后谢谢作者能给大家提供一个如此方便的看番软件！

**Comment by Predidit** [comment]
感谢你的反馈，相关逻辑会在下个版本中加入，我最近比较繁忙，更新应该会在下周到来。

也欢迎您直接提交pr修复此问题，让我们一起将这个项目变得更好。
