### ISSUE TITLE
大大 能出个TV版吗 

### ISSUE THREAD

**Issue by vcxvcxvxc** [Predidit/oneAnime#18]
大大 能出个TV版吗  鼠标真的不好操作

**Comment by vcxvcxvxc** [comment]
> 大大 能出个TV版吗 鼠标真的不好操作

还有。。在TV使用弹幕无法使用。。也没法选择集数 如果不打算做也无妨  再次感谢大大的贡献

**Comment by Predidit** [comment]
#16 

下一个项目会使用 Jetpack compose 来进行开发，应该会对 androidTV 有较好的支持

**Comment by vcxvcxvxc** [comment]
> #16
> 
> 下一个项目会使用 Jetpack compose 来进行开发，应该会对 androidTV 有较好的支持

感谢大大
