### ISSUE TITLE
报错提示为“RangeError (index): Invalid value: Valid value range is empty: -1”

### ISSUE THREAD

**Issue by zhenxixianzai** [Predidit/oneAnime#19]
程序解压后，点开视频时提示“RangeError (index): Invalid value: Valid value range is empty: -1”。
尝试过解决途径：
1、下载oneAnime_windows_1.1.8.zip解压无报错，1.1.8版本下电脑直接打开/设置代理（设置host为 127.0.0.1，设置port为 7890/10808），问题存在；
2、1.1.8版本下电脑连接wifi问题存在；
3、1.1.8版本下更换网络为手机热点，可以进入播放界面，但平均要缓存1分钟以上才有画面。
4、由于先前有人提出1.1.5版本之后存在同样报错问题，尝试使用1.1.4版本。1.1.4版本下电脑连网线或wifi打开，问题仍存在；
5、但是1.1.4版本连接热点同样可进入播放界面，但5分钟内都未出画面。
6、另外电脑连接网线的情况下，使用mumu模拟器打开1.1.8版本apk，也是同样问题。
辛苦排查问题

**Comment by Predidit** [comment]
我的想法和之前一样，这应该是一个网络方面的问题。

但是目前这个错误提示不够精确，我会在下个版本中完善这里的错误提示，到时麻烦您再提供一下报错信息。

**Comment by zhenxixianzai** [comment]
好的，我也认为应该是网络的问题，热点能连接证明这点。

**Comment by Predidit** [comment]
1.1.9 已经发布，现在有更详细的错误提示

**Comment by zhenxixianzai** [comment]
未开代理，提示网络连接超时；
代理下（设置主机为127.0.0.1，设置端口为7890），提示连接错误；
代理下（设置主机为127.0.0.1，设置端口为10808），提示正在使用局域网，网络异常；

**Comment by zhenxixianzai** [comment]
不好意思，可能找到原因了，我刚才测试了电脑直接连接光猫，虽然卡顿非常严重，但确实能打开了。
