### ISSUE TITLE
windows的改进意见

### ISSUE THREAD

**Issue by eirueirufu** [Predidit/oneAnime#2]
非常感谢作者的付出，这是我刚开始体验时觉得可以改进的地方：
1. 搜索框的圆角改成正角的是不是好点
2. 为什么没有窗口标题栏，拖动窗口的地方没有，需要切换到其他页面才能拖动
3. 程序关闭按钮放在搜索栏里感觉好奇怪
4. side bar右边空白好多

**Comment by Predidit** [comment]
感谢你的反馈

当我回复这个 Issue 时，1.1.2版本已经打包好了，故这些问题预期将于 1.1.3 中解决，1.1.2几乎完美解决了弹幕匹配问题，如果仍然有番剧存在弹幕匹配问题，欢迎给我留言

目前的圆角已经几乎没有弧度，完全的正角不是非常符合 Material You 规范

隐藏标题栏是为了界面的整洁，并防止调整窗体大小导致布局混乱，我会在下个版本中添加开关，可以切换系统标题栏和本程序的自定义标题栏

sidebar的空白问题来自 flutter 默认组件库，我会尝试编写自定义的侧边栏来让他更加美观

**Comment by Predidit** [comment]
侧边栏重构已在 1.1.3 完成
