### ISSUE TITLE
正在使用局域网网络异常

### ISSUE THREAD

**Issue by Ldz6890** [Predidit/oneAnime#21]
![PixPin_2024-05-17_14-19-27](https://github.com/Predidit/oneAnime/assets/153511282/f3f582b0-cdbe-4a46-8740-cea6b44946ce)
windows端（1.1.9），正在使用局域网网络异常，是什么意思呢？

时间表里的可以正常观看

**Comment by Predidit** [comment]
可能是刷新太频繁, 被番剧目录API屏蔽了。

重新给宽带拨一下号, 换一个 IP, 应该就好了。
