### ISSUE TITLE
關於Bangumi 的進度管理

### ISSUE THREAD

**Issue by NeKoOuO** [Predidit/oneAnime#23]
因為看到作者有用到Bangumi 我在想是不是能做一個一鍵追番的功能

大概的意思就是在這個APP裡面加入點格子的功能 就是看完一集就可以直接點看過 能夠同步追番進度到 Bangumi

**Comment by Predidit** [comment]
oneAnime 代码的扩展性不怎么好，编写时很多事情没有考虑到。

加上大陆和港澳台地区番剧译名的差别，在数据同步上应该会有较高的复杂度。

所以oneAnime应该是不会添加进度管理了，但是另一个项目 `Kazumi` 应该会在后续版本加入该功能。

**Comment by NeKoOuO** [comment]
譯名的部分 大部分的條目都會有別名 所以基本上用open cc繁簡+正則方法同時來搜正名+別名 基本都找的到

**Comment by NeKoOuO** [comment]
Kazumi 確實看起來擴展性很好 js寫個ani1的就可以代替原本的了😆
