### ISSUE TITLE
可否在播放器中加入集数选择按钮？

### ISSUE THREAD

**Issue by zhouqiubin** [Predidit/oneAnime#26]
在车机中安装，车机强制横屏，点击动画标题后进入播放页面时，播放器会充斥整个画面（未点击全屏按钮），无法点击下面的集数图标切换集数，全屏后播放键旁边只有下一集按钮无法返回上一集。请问可否在播放器中加入集数菜单按钮来进行集数切换操作？

**Comment by Predidit** [comment]
能看到下面的 `合集: 正在播放xxxx` 那一栏吗。那个 `全x话` 的标签在宽屏设备上是可以点开的，那个是集数菜单

**Comment by zhouqiubin** [comment]
> 能看到下面的 `合集: 正在播放xxxx` 那一栏吗。那个 `全x话` 的标签在宽屏设备上是可以点开的，那个是集数菜单

悲……看不见，播放器全屏和非全屏显示的区域一致

**Comment by Predidit** [comment]
这个功能会添加在下个版本中。

**Comment by zhouqiubin** [comment]
> 这个功能会添加在下个版本中。

感恩的心
