### ISSUE TITLE
"播放设置"中关闭“自动播放”时，进入视频页面，点击播放按钮后不会播放弹幕

### ISSUE THREAD

**Issue by IceTeaManiac** [Predidit/oneAnime#32]
问题原因似乎是点击播放按钮时 [这里](https://github.com/Predidit/oneAnime/blob/c558d2d2fcc61188c46d6f076818ff5bd911d7ba/lib/pages/player/player_controller.dart#L249) 调用了 `danmakuController.resume()` 函数来播放弹幕。

但是播放弹幕的 `resume` 函数本质上只是个根据当前状态切换播放和暂停的 [pauseResumeDanmakus](https://github.com/Predidit/canvas_danmaku/blob/aabfa821d1477fd170bed679897e2feb4643e8f4/lib/danmaku_screen.dart#L225) 函数。

刚进入页面时，弹幕内部的播放状态 [_running](https://github.com/Predidit/canvas_danmaku/blob/aabfa821d1477fd170bed679897e2feb4643e8f4/lib/danmaku_screen.dart#L62) 默认是 `true`，这导致了点击播放按钮调用 `resume` 函数实际上是将弹幕的播放状态变为了 `false`，从而导致弹幕播放失败。

目前感觉比较好的修复方式或许是改一下 canvas_danmaku 的 `resume` 函数的实现？

**Comment by IceTeaManiac** [comment]
看了下代码，canvas_danmaku 里面有[部分逻辑](https://github.com/Predidit/canvas_danmaku/blob/aabfa821d1477fd170bed679897e2feb4643e8f4/lib/danmaku_screen.dart#L98) 没搞明白，可能暂时提不了 PR。

**Comment by Predidit** [comment]
此问题已经通过 [52d50a](https://github.com/Predidit/canvas_danmaku/commit/52d50a4d8066d9aef0eceaa0d7839a72a1ca0380) 修复
