### ISSUE TITLE
Crash on Linux Platform

### ISSUE THREAD

**Issue by Predidit** [Predidit/oneAnime#34]
在升级到 flutter 3.22 后，通过 github actions 编译的 Linux 平台二进制文件无法正确启动。

此问题疑似与 leanflutter/window_manager#460 相关。

本地 Linux 环境编译的二进制程序可以正确启动，目前发布的 Linux 二进制文件为本地手动构建的版本。

**Comment by Predidit** [comment]
@IceTeaManiac 我注意到您之前似乎遇到过这一问题，您方便和我确认一下吗。

1. 当前发布的 Linux 手动构建版本是否可以在您的环境中正确运行。
2. 您使用 flutter 3.22.2 进行的手动构建是否可以正确运行。

**Comment by IceTeaManiac** [comment]
Linux 下 crash 的问题应该是和这个 [issue](https://github.com/media-kit/media-kit/issues/852) 有关，目前可以通过降级到 flutter 3.19.6 解决这个问题。

**Comment by IceTeaManiac** [comment]
我下载了 release 1.2.4 的 Linux 可执行文件，目前还是存在 crash 的情况。

触发条件是在播放视频时，鼠标在下方的多个选集按钮上来回移动。

如果在你那边目前已经无法再复现问题了的话，那么这个问题或许和特定的 Linux 环境下的底层依赖有关（如显卡驱动什么的）。

**Comment by Predidit** [comment]
我复现了此问题。

我在一台基于 AMD 4800U 的老旧平台上测试了 Linux 构建，系统为 Manjaro。

在使用 media_kit 时，硬件与软件解码均会导致前面提到的崩溃。在使用新的 mdk 库时，由于 mdk 支持指定硬件编解码器，所以我尝试了不同的组合，像是下面这样。

```
  registerWith(options: {
    'video.decoders': ['FFmpeg:codec=h264_mediacodec:hwaccel=mediacodec:hwcontext=mediacodec'],
    }
  },);
```

令人意外的是，当使用了与硬件不兼容的编解码器导致视频输出损坏时(仅音频)，此bug不会触发。

我现在对这个问题感到非常迷茫。mdk库移除了调试标记，我没有得到太多有价值的信息。虽然我不想那么说，但这看上去这像是 flutter 的问题，也许他们在linux平台上迁移到 gtk4 的努力破坏了一些东西。flutter官方不接受包含第三方库的bug回报，官方的 video_player 并未支持linux平台。

也许我可以尝试复现这一问题并报告给mdk的维护者。
