### ISSUE TITLE
希望能添加简体中文的资源

### ISSUE THREAD

**Issue by canmeng0110** [Predidit/oneAnime#35]
希望能添加简体中文的资源，可以的话 搜索内容显示也是简体就无敌了。

**Comment by Predidit** [comment]
anime1 是提供繁体资源的站点，所以作为第三方客户端，提供的资源也只能是繁体的。

如果需要简体资源的话，可以参考作者的另一个项目 [Kazumi](https://github.com/Predidit/Kazumi)
