### ISSUE TITLE
暂停播放、回退快进、锁定屏幕等

### ISSUE THREAD

**Issue by Eyion** [Predidit/oneAnime#37]
软件版本
1.2.3（Windows/Android）

问题描述（双端）
1. 播放时不能通过单击或双击屏幕完成暂停与播放、回退与快进等操作（双端）
2. 播放时不能锁定屏幕，以防止误触等（双端）
3. 软件界面偶尔会卡住，无法进行任何操作，只能杀进程（Windows）

**Comment by Predidit** [comment]
1. 双击快进/快退 会添加到 1.2.4 版本中
2. 没有计划添加锁定屏幕功能
3. 什么特定操作会触发 windows 平台上进程冻结的问题，冻结的发生是否存在规律

**Comment by Predidit** [comment]
我尝试排查了一下 windows平台的冻结问题。

我现在怀疑这一问题可能和 media-kit/media-kit#842 相关。

实际上我这边的设备无法复现冻结的问题，所以我需要一些更详细的信息。

我想确认一下，冻结是不是只在播放器初始化，以及切换选集时发生。

**Comment by Eyion** [comment]
目前只在‘历史记录页面’返回‘我的’页面时发生过。
另外，番的源和清晰度都只有一种吗，所以无需选择，有时播放加载时间比较长。

**Comment by Predidit** [comment]
本项目是 anime1 的第三方客户端。

作为第三方客户端开发者，我们无法控制 anime1 站点的码率和链路质量。

清晰度切换这类 anime1 自身没有提供的功能，我们是无法提供的。

此外，前面提到的崩溃是发生在点按返回按钮时吗

**Comment by Eyion** [comment]
整个界面的都点不了，包括返回和关闭，只能杀进程退出

**Comment by Predidit** [comment]
1.2.4 版本修复了闪退问题。

新增播放器手势操作需要等待下个版本相关模块的重构。

**Comment by Predidit** [comment]
1.2.5 新增手势和快捷键操作
