### ISSUE TITLE
【优化体验】支持快捷键、加入音量键和进度的控制

### ISSUE THREAD

**Issue by macj2010** [Predidit/oneAnime#38]
很感谢这么一款软件，让我很容易就可以追番。不用登录绝对是亮点，请继续保持。

版本：【v1.2.4】
平台：Windows 11

目前功能都很满意，就是习惯了快捷键的使用，比如方向键的上/下代表音量的加减（最好把音量的控制按钮放出），方向键的左/右代表快进/快退（已有），空格代表暂停/播放（已有），f代表全屏，d代表开关弹幕，这些都是b站的使用习惯，但是入二次元的很少不用b站吧。

以上只是一些优化建议，不是最重要的，希望得空的时候可以加入。

**Comment by Predidit** [comment]
音量加减现在是绑定在鼠标滚轮上的。

空格暂停/播放已有。

F/D 快捷键将会在 1.2.5 版本中加入

PS: 最新版本是 1.2.4 不是 1.2.6

**Comment by Predidit** [comment]
1.2.5 已经发布
