### ISSUE TITLE
在Windows 1.2.5中，软件自动崩溃

### ISSUE THREAD

**Issue by SajoSinGyoku** [Predidit/oneAnime#40]
软件可以正常开启，但是在点击番剧后显示正在加载然后便崩溃

**Comment by Predidit** [comment]
听上去是视频解码的问题。

设置选项卡里的播放设置，尝试关闭硬件解码选项并重启程序。

另外方便告知我您的CPU和GPU配置吗

**Comment by SajoSinGyoku** [comment]
cpu是i5 13500h
gpu是Xe Graphics
在关闭硬件解码后，1.2.5依旧无法运行，同时测了下1.2.4，在关闭硬件解码的情况下也无法正常运行，1.2.1~1.2.3未测试。
1.2.0无论是否开启硬件解码都可以正常播放

**Comment by Predidit** [comment]
1.2.0版本之后的程序会使用 windows MediaFoundation API，也就是 windows 自带应用 电影和电视 相同的实现，你能用这个自带程序打开任意 mp4 视频吗。

另外，操作系统版本是？

**Comment by Predidit** [comment]
好的，但是我这边并没有和您相同型号的设备可供测试，暂时复现不了这个问题/

您尝试过更新Xe核显的驱动吗，这可能会解决问题。

如果问题仍然无法解决的话，我会在下个版本加入Intel主导的编解码库 VAAPI 的支持，应该会有用。

**Comment by SajoSinGyoku** [comment]
目前xe核显驱动是最新版本，现在看来只能等下个版本了

**Comment by Predidit** [comment]
[oneAnime_windows_VAAPI.zip](https://github.com/user-attachments/files/15952645/oneAnime_windows_VAAPI.zip)

我手动构建了一版本使用 VAAPI 的程序，方便测试一下这个构建能否正确运行吗，包括开启与关闭硬件解码的情况。

**Comment by SajoSinGyoku** [comment]
不行，开启与关闭硬件解码均无法正常播放

**Comment by Predidit** [comment]
我现在对这个问题感到非常困惑，稍后我会尝试构建一般带有 调试日志输出 功能的程序。您方便的话，到时可以提交日志给我。

**Comment by Eyion** [comment]
安卓端搜索“鬼灭之刃”也发生闪退

**Comment by leiyuta** [comment]
您好，windows1.2.4和1.2.5均有楼主相同问题，1.2.3可以正常播放。我的设备是RTX3060，2th Gen Intel(R) Core(TM) i7-12700H   2.30 GHz

**Comment by Predidit** [comment]
> 您好，windows1.2.4和1.2.5均有楼主相同问题，1.2.3可以正常播放。我的设备是RTX3060，2th Gen Intel(R) Core(TM) i7-12700H 2.30 GHz

使用Intel核显播放有问题吗

**Comment by leiyuta** [comment]
> > 您好，windows1.2.4和1.2.5均有楼主相同问题，1.2.3可以正常播放。我的设备是RTX3060,2th Gen Intel（R） Core（TM） i7-12700H 2.30 GHz
> 
> 使用Intel核显播放有问题吗

不明白您的意思，我对于电脑方面没有这么懂，不知道如何使用核显播放

**Comment by Predidit** [comment]
这看上去是一个和 NVIDA 显卡相关的问题，由于涉及到播放器的底层，我并不能立即修复这个问题，

当有进展时，我会在这个Issue进行更新。

对于受影响的使用者，我建议先使用 1.2.3 版本进行替代。

**Comment by Predidit** [comment]
1.2.6 版本已经发布，此问题应该得到解决。

**Comment by SajoSinGyoku** [comment]
> 1.2.6 版本已经发布，此问题应该得到解决。

解决了，非常感谢
