### ISSUE TITLE
正在使用wifi网络异常

### ISSUE THREAD

**Issue by llsmax2** [Predidit/oneAnime#42]
第一次用到本app是1.2.3，每次打开首页下面都会有一行小字 正在使用wifi网络异常，时间列表里的可以正常观看
我以为是自己的问题，就没再用了，等更新，现在1.2.5版本还是同样的问题，不论是否挂梯子都会出现，很困扰

**Comment by llsmax2** [comment]
pc端 Windows 10 21h2

**Comment by Predidit** [comment]
只要有网络请求失败，就会出现这个提示，有些失败的网络请求是无关紧要的，例如检查更新。

检查更新功能使用了 Github API。大陆地区访问可能有点问题。

如果软件功能可用，所有列表和资源可以正确加载，就不用管他。

**Comment by llsmax2** [comment]
> 只要有网络请求失败，就会出现这个提示，有些失败的网络请求是无关紧要的，例如检查更新。
> 
> 检查更新功能使用了 Github API。大陆地区访问可能有点问题。
> 
> 如果软件功能可用，所有列表和资源可以正确加载，就不用管他。

挂了全局梯子也不行，而且出现这个提示之后，搜索功能是完全不能用的

**Comment by Predidit** [comment]
全局梯子一般只影响浏览器这种使用系统代理的程序。其他的程序一般需要启用梯子的TUN功能。

**Comment by llsmax2** [comment]
> 全局梯子一般只影响浏览器这种使用系统代理的程序。其他的程序一般需要启用梯子的TUN功能。

开了tun 现在打开app之后的提示变成“网络连接超时，请检查网络”，总之谢谢您耐心解答
