### ISSUE TITLE
建议增加简体中文英文搜索，和清晰度选项

### ISSUE THREAD

**Issue by WenlongDai** [Predidit/oneAnime#43]
感谢分享！
繁体搜索需要先查繁体
现在看起来是720p，希望可以找到更清晰的源

**Comment by Predidit** [comment]
可以直接查简体的 (除了MacOS)

MacOS 的问题是flutter生态中可用的opencc简繁转换插件只支持Android和windows。这本来可以像 windows 那样通过FFI解决。但是没有相关的硬件设备可以供我调试FFI。所以暂时搁置。

关于视频源的问题，目前的代码和anime1的耦合程度是相当高的。anime1有着很特殊的架构，例如其基于在视频站点中很少见的 wordpress，奇怪的视频鉴权方案，奇怪的页面逻辑。

所以实际上这个项目切换到其他视频源是不太可能的。

如果想要其他的视频源，可用尝试一下作者的 Kazumi 项目。
