### ISSUE TITLE
播放中途卡住

### ISSUE THREAD

**Issue by leiyuta** [Predidit/oneAnime#45]
版本1.2.6。在番剧播放途中，会突然开始转圈，并且不会继续播放，此时左上角退出后重进可以恢复。但是稳定播放一段时间后又会出现该问题，出现次数很频繁。还有一个问题是，部分番剧在打开后虽然播放，但是中间的转圈不会停止，就是播放的同时在转圈，而且进度条始终显示0，拖动进度条后会从头开始播放。在anime1网站上播放均不会出现上述问题

**Comment by Predidit** [comment]
突然开始转圈并停止，是视频流卡住了，这是一个网络相关的问题，可能你的本地网络到 anime1 的连通性不是很好。程序默认是不走代理的，浏览器访问时走代理，所以浏览器访问没有问题。

部分番剧打开后转圈不停止，是哪些番剧呢，能稳定复现吗。

**Comment by leiyuta** [comment]
<img width="954" alt="1" src="https://github.com/user-attachments/assets/ebb4fa89-aa1a-4f26-9c60-7c7786f82607">
这里《我推的孩子》出现了进度条为0且拖动会导致从头播放的问题，但是转圈倒是消失了，之前物语系列也有同样的问题，但是未能复现，前几天问题出现得比较稳定。

**Comment by leiyuta** [comment]
> 突然开始转圈并停止，是视频流卡住了，这是一个网络相关的问题，可能你的本地网络到 anime1 的连通性不是很好。程序默认是不走代理的，浏览器访问时走代理，所以浏览器访问没有问题。
> 
> 部分番剧打开后转圈不停止，是哪些番剧呢，能稳定复现吗。

前面说的视频流卡住问题有什么比较好的解决方案吗，比如我现在用的校园网，使用家庭网络就有可能解决还是说要使用VPN

**Comment by Predidit** [comment]
家庭网络应该就可以解决。

我在 windows 平台没有复现 《我推的孩子》卡住的问题，你在使用 Mac 吗？

**Comment by leiyuta** [comment]
> 家庭网络应该就可以解决。
> 
> 我在 windows 平台没有复现 《我推的孩子》卡住的问题，你在使用 Mac 吗？

我使用的是Windows

**Comment by Predidit** [comment]
此问题应该在新发布的 1.2.8 版本中修复，检查是否还有问题。
