### ISSUE TITLE
ios提示301错误

### ISSUE THREAD

**Issue by AlanDinkle** [Predidit/oneAnime#49]
unable to locate the app bundle inside the ipa archive

**Comment by Predidit** [comment]
构建脚本写错了，明天会发一版来修复。

**Comment by 0212908** [comment]
你解壓縮看 會發現目錄多了幾層
你可以找正常的ipa看就知道目錄
刪掉目錄後重新zip壓縮 改名ipa就能安裝了

**Comment by Predidit** [comment]
1.3.1 版本发布，应该修复了

**Comment by Predidit** [comment]
> > 1.3.1 版本发布，应该修复了
> 
> 是的可以安装了，但是非常卡顿，进入播放界面后直接卡死，不能有其他操作

哪款设备，试试关闭硬件解码。

**Comment by 0212908** [comment]
我兩台設備可以撥放 不過是用1.3.0 但是有bug 有切換硬軟解 無關
一台ipad9 ios15 可以橫屏撥放 但是播放後 會全比例會變4:3占滿螢幕 和控制介面消失 無法回上頁
一台iph12 ios16 全螢幕後只能直屏  這可能是ios16的bug 當初升上ios16時 很多撥放軟體直橫屏異常 後來app升級才解決該bug
一樣控制介面會消失

**Comment by Predidit** [comment]
我知道问题出在哪里了，会在下个版本解决。

**Comment by Predidit** [comment]
补丁已经提交到仓库。

其对应的ipa文件为 https://github.com/Predidit/oneAnime/actions/runs/10438595273/artifacts/1824153005

检查这个版本有无问题。

**Comment by 0212908** [comment]
上面那版可以了 謝謝 
剩控制介面撥放時會消失無法再叫出 不過回首頁重開 就出現了

**Comment by Predidit** [comment]
全屏和非全屏模式下都无法再叫出吗

**Comment by 0212908** [comment]
你好 對 都不能叫出 但能用往左往右划手勢時間 不過看不到時間條

兩台設備狀況不太一樣
iph12 需要回首頁 再重新打開 會出現控制條 這時可以跳出 可以16:9 左右旁邊黑邊 這樣正常
跟ipad不同的是 直得拿時 影片還是橫屏
ipad9 重開 控制條只能短暫出現 約0.幾秒 全螢幕時強制全螢幕 直的拿時 影片就變成直的 比例會很怪
16:9的影片會變3:4

**Comment by 0212908** [comment]
你好 我看到別人寫的bug 但你上面那個網址下載的橫直屏bug有修正
不會強制直屏了 我的問題是直屏因為畫面佔滿螢幕 畫面比例很怪

**Comment by Predidit** [comment]
我提交了新的补丁，对应的构建链接为

https://github.com/Predidit/oneAnime/actions/runs/10447698607/artifacts/1825976865

检查这个版本是否还有问题

**Comment by 0212908** [comment]
謝謝 修正好比例了 ipad直橫屏 都是16：9正常播放
目前控制條暫時解法 
就是回首頁重開app 影片會自動暫停 控制條就出現了 不然影片無法暫停
兩者設備都可以

**Comment by Predidit** [comment]
我想到了可能的原因，我会在明天继续发布一个实验性构建来尝试修复控制栏问题。

**Comment by Predidit** [comment]
https://github.com/Predidit/oneAnime/actions/runs/10464933025/artifacts/1830563818

检查这个构建是否可以呼出控制栏

**Comment by 0212908** [comment]
可以顯示了 但是沒有聲音 前面版本有聲音的

**Comment by Predidit** [comment]
手动用实体按键调节音量也不行吗

**Comment by 0212908** [comment]
手勢或按鍵試過了
連藍芽卻有聲音
沒連時 測試過yt有聲音

**Comment by Predidit** [comment]
音量控制相关的代码没有动过，检查iOS情景模式

**Comment by 0212908** [comment]
對 旁邊的靜音按鈕打開了 但是我打開 其他撥放器可以有聲音的
不過關閉就能用了 謝謝

**Comment by Predidit** [comment]
看上去 iOS 相关问题已经全部解决了，我会在明天合并另一个无关 iOS 的修改后发布新版本。

**Comment by Predidit** [comment]
1.3.2 版本发布，此问题解决
