### ISSUE TITLE
小米8 搜索闪退

### ISSUE THREAD

**Issue by Eyion** [Predidit/oneAnime#50]
软件版本
 1.3.0

手机系统 
安卓 

问题
在搜索框输入内容后，点搜索即闪退

**Comment by Predidit** [comment]
最新版本是 1.3.1 

检查最新版本有无问题

**Comment by Eyion** [comment]
1.3.1 目前未再出现闪退。
另，每次更新，历史记录会保存吗？

**Comment by Predidit** [comment]
会保留的

**Comment by Eyion** [comment]
之前没留意安卓端是否保留，但win端好像没了

**Comment by Predidit** [comment]
保留的。

保存在 `%AppData%/com.example/kazumi/`

可能是使用了什么奇怪的清理软件把这个文件夹下的内容清理掉了
