### ISSUE TITLE
ios端全屏播放无法横屏。

### ISSUE THREAD

**Issue by Tusk0214** [Predidit/oneAnime#51]
ios端播放器全屏播放时无法横屏，而是竖屏并拉伸了画面。

**Comment by Predidit** [comment]
尝试 #49 中发布的实验性构建，并确认有没有 #49 中提到的控制面板无法呼出的问题。

**Comment by 0212908** [comment]
你好 你下載另一串網址的ipa試試看
我想另外問 你控制調播放後能再次顯現嗎

**Comment by Predidit** [comment]
1.3.2 版本发布，此问题解决。
