### ISSUE TITLE
ios上 影片播放速度沒法固定

### ISSUE THREAD

**Issue by 0212908** [Predidit/oneAnime#52]
我如果設兩倍速（比較明顯差異 用兩倍測）
播放時兩倍速 暫停再播放是能恢復兩倍速
但是如果是滑動時間調 改不同播放時間進度
就會恢復一倍速
我可能以為就是這樣設計的 只是要再次按兩倍速
但是我用安卓測試卻沒此bug

**Comment by Predidit** [comment]
这似乎是 android 和 iOS 底层音视频套件的差异。

也就是 Android ExoPlayer 和 Apple AVPlayer 的某些行为不同。这些套件由 Google 和 Apple 维护，他们对来自外部开发者的大部分提案不感兴趣。 

如果要修复的话，我只能在上层进行 workaround 。例如在每次 seek 之后设置播放倍速为之前的速度。这很不优雅，所以我暂时没有修复这一问题的打算。
