### ISSUE TITLE
希望增加ARMv7支持

### ISSUE THREAD

**Issue by Ludwig-OG** [Predidit/oneAnime#54]
软件很好用，希望可以在电视上安装还用

**Comment by Predidit** [comment]
电视上用其他软件好一些。

Android TV 的适配心智负担很高，暂时没有计划。用现有版本的话，操作还要配合鼠标。

实在想要 armv7 版本的话，可以 fork 这个仓库，稍微修改 workflow 脚本，用 github actions 来云构建就可以了。
