### ISSUE TITLE
Android 版本修改建議

### ISSUE THREAD

**Issue by skyxwind** [Predidit/oneAnime#6]
1. 對平板電腦橫向介面優化，目前1.1.4版本會有無法切換集數的問題
2. 將歷史紀錄與追番合併，有按愛心置頂顯示
3. 新增純黑配色（AMOLED）
目前使用沒發現什麼bug，感謝開發者的付出！
（私心希望有繁體中文化直翻也可以，對繁體使用者有很大的幫助

**Comment by Predidit** [comment]
1. 程序本身在安卓设备上是为竖屏优化的，不建议在平板电脑上使用强制横屏功能，这可能会导致一些无法预期的 bug。不过可以留下您的平板电脑的屏幕宽高比例，有助于我们解决问题。

2. 这个目前没有计划，这种改动侵入性比较高，而且作者个人觉得现在的设计好一些。

3. 你尝试过将外观设置里的主题模式改为深色吗，我也在使用 AMOLED 设备，深色模式下应该能发挥 AMOLED 省电的特性。

4. 关于本地化，本来本项目就是一个 anime1 的第三方客户端，需要支持繁体中文是理所当然的。但是现有的 flutter 本地化方案都较为繁琐，本地化支持的加入需要时间，但预期可以在几个版本内完成。

**Comment by skyxwind** [comment]
感謝作者的迅速回覆
關於平板電腦，我使用的是 Samsung Galaxy Tab S8 比例為16：10
關於純黑配色，可以參考LibreTube的純粹黑/白模式，將背景底色以接近純黑顯示
我是常駐深色模式的，個人感覺背景還是偏亮了些，若以純黑顯示比較不刺眼

**Comment by Predidit** [comment]
我需要再确认一下

第一个Bug是什么情况下触发的，使用平板电脑的强制横屏后触发，还是使用播放器本身的全屏功能后触发

**Comment by skyxwind** [comment]
平板設為自動旋轉，在主選單以橫向點選影片播放，下方的選集無法使用僅呈現「合集 正在播放：」這一欄位，轉為直向時選集介面有出現

Uploading Screen_Recording_20240406_104715.mp4…

**Comment by skyxwind** [comment]
![Screenshot_20240406_105451](https://github.com/Predidit/oneAnime/assets/103808206/68927dd5-7636-44a4-8ee7-f6135dd14164)
![Screenshot_20240406_105441](https://github.com/Predidit/oneAnime/assets/103808206/58a7bcd8-5895-4cd0-837e-76b112160a91)

https://github.com/Predidit/oneAnime/assets/103808206/eb1ee8b9-e80c-44d9-b3b2-31a0ca70bffd

**Comment by Predidit** [comment]
好的，感谢你详细的反馈，我明白了

其实这个就是第一次回复里说的无法预期的Bug，程序在安卓设备上为横屏优化，并设定为不响应系统的自动旋转功能

Samsung 平板基于某些考量，自动旋转功能似乎会忽略应用程序设置的偏好，而强制旋转应用程序。程序没有考虑被强制旋转的情况，这导致了问题

我需要考虑一下有没有什么比较合适的修复

**Comment by skyxwind** [comment]
個人有個小想法：
讓軟體在偵測橫向時，令圖中「全一話」的按鈕能點擊，跳出彈出選單進行選集

不確定難不難達成，只是提供一個想法供作者參考

**Comment by Predidit** [comment]
这个非常好达成，是非常容易的解决方案。

我现在在考虑到方案是在安卓平板上套用 PC 的播放器页面布局，你觉得这两种方案，哪种方案好一点呢。

**Comment by skyxwind** [comment]
在試用了電腦版佈局，我覺得使用彈出視窗方式較電腦佈局易於觸控操作，電腦佈局的選集滾動方式可能會拉到系統手勢

**Comment by Predidit** [comment]
感谢你的 issue 让这个项目变得更好，此改动会包含在下次更新中

**Comment by Predidit** [comment]
关于第三点，你认为播放器全屏模式下的黑边是类似 LibreTube 的纯粹黑吗

这是本程序中为数不多直接定义了颜色为纯黑色(0xFF000000)的地方

如果你觉得效果类似与 LibreTube，那应该可以实现其他地方背景色的调整，如果仍然有差距，我可能就无能为力了

**Comment by skyxwind** [comment]
是的

**Comment by Predidit** [comment]
OLED优化与平板横屏模式下的剧集切换，已经在 1.1.5 版本中完成。

本地化适配工作在日程上，预期会在几个版本内完成。

如果显示效果与分集切换没有问题的话，我会在今天稍晚时候关闭此 Issue。
