### ISSUE TITLE
无法播放视频

### ISSUE THREAD

**Issue by Qing-Novel** [Predidit/oneAnime#60]
不管是挂梯子（香港节点）还是不挂梯子都无法播放视频，不知道该怎样才能播放视频

https://github.com/user-attachments/assets/286f667a-7403-4322-9b76-48d2aa8c3182

**Comment by Predidit** [comment]
播放设置里关掉硬件解码试试

**Comment by Qing-Novel** [comment]
> 播放设置里关掉硬件解码试试

好的，我试下看看有没有改观

**Comment by Qing-Novel** [comment]
> 播放设置里关掉硬件解码试试

可以了，感谢解答

**Comment by Predidit** [comment]
这个 Issue 现在关闭，硬件解码不可用的问题在 kazumi 的相关 Issue 里追踪。
