### ISSUE TITLE
打开软件是开屏页状态栏部分是灰色而不是跟其他部分一样的白色

### ISSUE THREAD

**Issue by Qing-Novel** [Predidit/oneAnime#64]
打开软件是开屏页状态栏部分是灰色而不是跟其他部分一样的白色
![Videoframe_20241008_102831_com huawei himovie local](https://github.com/user-attachments/assets/d5a50223-42e4-4592-b722-7aa436ef3325)

https://github.com/user-attachments/assets/ec998d3a-aede-430c-93a5-6142cad3ef01

**Comment by Predidit** [comment]
在 kazumi 相关问题中追踪
