### ISSUE TITLE
大佬 我想问下 联通是不是用不了

### ISSUE THREAD

**Issue by vcxvcxvxc** [Predidit/oneAnime#68]
记得是1.2X哪个版本开始。。用联通打开就一直转圈圈 而且毫无速度 换成手机电信 直接秒开。。。

**Comment by Predidit** [comment]
老版本的 oneAnime 现在也能下载

如果老版本的现在没有播放问题，我可能可以给出一些建议

如果老版本的也有播放问题，那就是网络问题，没什么好办法

**Comment by vcxvcxvxc** [comment]
> 老版本的 oneAnime 现在也能下载
> 
> 如果老版本的现在没有播放问题，我可能可以给出一些建议
> 
> 如果老版本的也有播放问题，那就是网络问题，没什么好办法

没事 我只是说下 我已经把1.1开始的全部版本试试 看看是哪个版本开始
