### ISSUE TITLE
oneanime闪退

### ISSUE THREAD

**Issue by Qing-Novel** [Predidit/oneAnime#71]
aosp10 鸿蒙2 华为m6高能版
打开oneanime后点开一个番剧，没加载出画面就闪退了

**Comment by Qing-Novel** [comment]
不知道是不是偶发性闪退，设置里貌似没有错误日志所以没法复制过来

**Comment by Predidit** [comment]
这是一个已知问题，来自华为 AOSP 设备的 vulkan 驱动缺陷

**Comment by Qing-Novel** [comment]
> 这是一个已知问题，来自华为 Android10 设备的 vulkan 驱动缺陷

好的

**Comment by Predidit** [comment]
在 1.3.7 修复
