### ISSUE TITLE
AppImage build for Linux

### ISSUE THREAD

**Issue by zqigolden** [Predidit/oneAnime#74]
我在测试1.3.7 linux版本时候注意到一些系统环境不一致（如glib版本）会导致程序不能运行。

尝试通过AppImage构建，能够解决我遇到的环境问题。
这里有一个可以用来测试的[build](https://github.com/zqigolden/oneAnime/actions/runs/12382734560)，
有帮助的话我可以提一个整合到release CI的PR。

**Comment by Predidit** [comment]
谢谢你的工作，我们欢迎PR

**Comment by zqigolden** [comment]
https://github.com/Predidit/oneAnime/pull/75

**Comment by zqigolden** [comment]
测试了linux build可以通过，在apk sign fail了，应该没问题
