### ISSUE TITLE
Windows版播放界面选集问题

### ISSUE THREAD

**Issue by songbirdzz** [Predidit/oneAnime#9]
当番剧集数较多时（例如集数超过两行），鼠标滚轮滑动一次后，播放界面下方的选集会超过第二行而滑到第二行与第三行中间。例：

![image](https://github.com/Predidit/oneAnime/assets/165868972/4458aa9b-abc2-49f3-80ef-1f0731fa80cf)

**Comment by Predidit** [comment]
关于这个问题，我的想法是监听鼠标滚动事件，配合 scrollerController 的 jump 方法跳转到列表的指定位置。

稍晚的时候我尝试实现一下。

或者有什么更好的想法？

**Comment by songbirdzz** [comment]
直觉上来说的话，第一反应是允许用户拖拽窗口大小，上面的player部分根据长/宽中较小者适配（当然也考虑比例），然后剩下的页面大小留给选集部分。不过不知道用flutter实现起来困不困难。
